server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

api:
  prefix: api

app:
  base-url: ${APP_BASE_URL:http://localhost}

jwt:
  expiration: 36000
  secretKey: ${JWT_SECRET_KEY}

# File Upload Configuration
file:
  upload:
    path: ${FILE_UPLOAD_PATH:uploads/}
    allowed-types: jpg,jpeg,png,gif,webp,pdf
    max-size: 10485760 # 10MB in bytes
    avatar:
      width: 200
      height: 200
    house-image:
      width: 800
      height: 600
    thumbnail:
      width: 150
      height: 150
    proof-of-ownership:
      width: 800
      height: 600

logging:
  level:
    root: INFO
    com.codegym: DEBUG
    org.springframework.security: INFO
    org.springframework.security.web: INFO
    org.springframework.security.authentication: INFO
    org.springframework.security.oauth2: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/rental-house.log
    max-size: 10MB
    max-history: 30
