server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        use_sql_comments: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com

api:
  prefix: api

app:
  base-url: ${APP_BASE_URL:http://localhost}

jwt:
  expiration: 36000
  secretKey: ${JWT_SECRET_KEY}

# File Upload Configuration
file:
  upload:
    path: ${FILE_UPLOAD_PATH:uploads/}
    allowed-types: jpg,jpeg,png,pdf
    max-size: 10485760 # 10MB in bytes
    avatar:
      width: 200
      height: 200
    house-image:
      width: 800
      height: 600
    thumbnail:
      width: 150
      height: 150
    proof-of-ownership:
      width: 800
      height: 600

logging:
  level:
    root: WARN
    com.codegym: INFO
    org.springframework.security: WARN
    org.springframework.security.web: WARN
    org.springframework.security.authentication: WARN
    org.springframework.security.oauth2: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{20} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/rental-house.log
    max-size: 5MB
    max-history: 7

# Google API Configuration
google:
  oauth:
    client-id: ${GOOGLE_OAUTH_CLIENT_ID:733951522739-l866o9ncig1ipqa5p15j5lod8l605m08.apps.googleusercontent.com}
  api:
    key: ${GOOGLE_API_KEY:}

