# Local development configuration
# Copy this file and add your email credentials for testing

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-gmail-address@gmail.com  # Replace with your Gmail address
    password: your-16-character-app-password  # Replace with your Gmail app password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.debug: true  # Enable debug for troubleshooting
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

# Database configuration for local development
  datasource:
    url: jdbc:mysql://localhost:3306/rental_house?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password

# JWT configuration
jwt:
  expiration: 36000
  secretKey: your-local-jwt-secret-key-change-this-in-production

# Application configuration
app:
  base-url: http://localhost:3000

# Google API Configuration
google:
  oauth:
    client-id: 733951522739-l866o9ncig1ipqa5p15j5lod8l605m08.apps.googleusercontent.com
  api:
    key: your-google-api-key-here

# File Upload Configuration
file:
  upload:
    path: uploads/
    allowed-types: jpg,jpeg,png,gif,webp,pdf
    max-size: 10485760 # 10MB in bytes

# Logging configuration for debugging email issues
logging:
  level:
    org.springframework.mail: DEBUG
    com.codegym.service.EmailService: DEBUG

